### ISSUE TITLE
openmeeg fails to build with hdf5 1.10.1

### ISSUE THREAD

**Issue by iMichka** [openmeeg/openmeeg#203]
Hi. We updated to the latest version of hdf5 in the homebrew-science package manager.

openmeeg fails to build with:

```
/tmp/openmeeg-20170512-4674-5237wh/openmeeg-release-2.1/contrib/matio/src/mat73.c:822:62: error: too few arguments to function call, expected 4, have 3
ref_ids+l);
^
/usr/local/include/H5Rpublic.h:61:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
^
/tmp/openmeeg-20170512-4674-5237wh/openmeeg-release-2.1/contrib/matio/src/mat73.c:971:72: error: too few arguments to function call, expected 4, have 3
refid = H5Rdereference(dset_id,H5R_OBJECT,ref_ids+i);
~~~~~~~~~~~~~~ ^
/usr/local/include/H5Rpublic.h:61:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
^
/tmp/openmeeg-20170512-4674-5237wh/openmeeg-release-2.1/contrib/matio/src/mat73.c:2621:77: error: too few arguments to function call, expected 4, have 3
ref_id = H5Rdereference(dset_id,H5R_OBJECT,ref_ids+i);
~~~~~~~~~~~~~~ ^
/usr/local/include/H5Rpublic.h:61:8: note: 'H5Rdereference2' declared here
H5_DLL hid_t H5Rdereference2(hid_t obj_id, hid_t oapl_id, H5R_type_t ref_type, const void *ref);
^
3 errors generated.
```

It seems that the HDF5 API has changed. Could you have a look at this?

**Comment by agramfort** [comment]
are you trying to build current master?

our travis with brew is green

**Comment by iMichka** [comment]
No we are only building binaries from stable tags, so release-2.1 it is.

You can build master on homebrew but we do not recommend this to our users, it is just for some developers that need to work with the latest version. But the stable binaries are always built from a tagger version. I am trying to build with --HEAD but I am hitting other errors which may be unrelated, I will need to investigate these too later.

**Comment by agramfort** [comment]
we just tagged a prerelease:

https://github.com/openmeeg/openmeeg/releases/tag/2.4.prerelease

does it help?

**Comment by iMichka** [comment]
We could live with the pre-release. Here are the errors I am getting with that pre-release:

```
[  7%] Performing download step (git clone) for 'zlib'
/usr/local/Cellar/cmake/3.8.2/bin/cmake -P /tmp/openmeeg-20170604-85713-1y6jgp6/openmeeg-2.4.prerelease/zlib/tmp/zlib-gitclone.cmake
/usr/local/Cellar/cmake/3.8.2/bin/cmake -P /tmp/openmeeg-20170604-85713-1y6jgp6/openmeeg-2.4.prerelease/zlib/tmp/zlib-gitclone.cmake
Cloning into 'zlib'...
fatal: destination path 'zlib' already exists and is not an empty directory.
fatal: destination path 'zlib' already exists and is not an empty directory.
fatal: destination path 'zlib' already exists and is not an empty directory.
-- Had to git clone more than once:
          3 times.
CMake Error at zlib/tmp/zlib-gitclone.cmake:66 (message):
  Failed to clone repository: 'https://github.com/madler/zlib.git'


make[3]: *** [zlib/stamp/zlib-download] Error 1
make[2]: *** [CMakeFiles/zlib-install.dir/all] Error 2
make[2]: *** Waiting for unfinished jobs....
Note: checking out 'v1.2.11'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at cacf7f1... zlib 1.2.11
Error copying file "/tmp/openmeeg-20170604-85713-1y6jgp6/openmeeg-2.4.prerelease/zlib/stamp/zlib-gitinfo.txt" to "/tmp/openmeeg-20170604-85713-1y6jgp6/openmeeg-2.4.prerelease/zlib/stamp/zlib-gitclone-lastrun.txt".
CMake Error at zlib/tmp/zlib-gitclone.cmake:109 (message):
  Failed to copy script-last-run stamp file:
  '/tmp/openmeeg-20170604-85713-1y6jgp6/openmeeg-2.4.prerelease/zlib/stamp/zlib-gitclone-lastrun.txt'


make[3]: *** [zlib/stamp/zlib-download] Error 1
make[2]: *** [CMakeFiles/zlib.dir/all] Error 2
make[1]: *** [CMakeFiles/install.dir/rule] Error 2
make: *** [install] Error 2
```

That's odd. I'll try to build it from outside of homebrew to see if this helps.

**Comment by agramfort** [comment]
with brew you should be building from the OpenMEEG folder not from the root
folder as brew has all the necessary dependencies.

I build with brew with this:

ccmake -DBUILD_SHARED_LIBS=ON -DENABLE_PYTHON=OFF -DBUILD_DOCUMENTATION=OFF
 openmeeg/OpenMEEG/

hope this helps

can I help with the brew script? do you have a PR somewhere?

**Comment by iMichka** [comment]
Ok got it to work, building from the OpenMEEG folder what the thing that fixed it.
Here is the pull request: https://github.com/Homebrew/homebrew-science/pull/5687
Thanks for the help.

I have 2 more questions:
- would there be a test that we could run to check if openmeeg runs. Something simple if possible.
- will the pre-release tag stay on this sha1, or will it move? I would prefer a stable tag, because if people rebuild from source, we are not able to guarantee that they will get a stable build if the tag is moved/deleted in the next days/months.

**Comment by iMichka** [comment]
I'm getting new errors in a clean env (buildbots):

> -- Found HDF5: /usr/local/lib/libhdf5.dylib;/usr/local/lib/libsz.dylib;/usr/local/opt/zlib/lib/libz.dylib;/usr/lib/libdl.dylib;/usr/lib/libm.dylib (found version "1.10.1")  
FATAL Unable to compile a simple matio program. Check your installation.
[[Looking for package: matio]]
CMake Error at /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:137 (message):
  Could NOT find matio (missing: matio_LIBRARY matio_INCLUDE_DIR)
Call Stack (most recent call first):
  /usr/local/Cellar/cmake/3.8.2/share/cmake/Modules/FindPackageHandleStandardArgs.cmake:377 (_FPHSA_FAILURE_MESSAGE)
  cmake/Findmatio.cmake:40 (find_package_handle_standard_args)
  /tmp/openmeeg-20170604-62002-dsgudj/openmeeg-2.4.prerelease/build/OpenMEEGDependencies.cmake:13 (find_package)
  /tmp/openmeeg-20170604-62002-dsgudj/openmeeg-2.4.prerelease/build/OpenMEEGDependencies.cmake:24 (find)
  cmake/GenerateConfigFile.cmake:78 (include)
  CMakeLists.txt:64 (Dependencies)

Do I need that special version of hdf5? (https://github.com/openmeeg/hdf5-matio)

**Comment by agramfort** [comment]
moving the conversation to https://github.com/Homebrew/homebrew-science/pull/5687

**Comment by iMichka** [comment]
I confirm that the pre-release correctly builds, and we were able to setup a working formula. Closing here.
