### ISSUE TITLE
BUG: Bugs with Python wrappers

### ISSUE THREAD

**Issue by larsoner** [openmeeg/openmeeg#584]
- [ ] Our Python API is not consistent. Sometimes you accept an array sometimes you don’t. If you screw up the shape it segfaults 
- [ ] If you don’t have a Fortran layout it should raise a nice exception
- [ ] We need to test better single layer model (#577)
- [ ] Constructing a Sensors object in Python is a mess
- [ ] Fix XXX in the tests

_Adapted from code posted by @agramfort in https://github.com/openmeeg/openmeeg/issues/564#issuecomment-1231541158_

**Comment by papadop** [comment]
For constructing sensors, we have to adopt the Geometry strategy (see %extend OpenMEEG::Geometry at the end of openmeeg.i). I think this is the only way to have a nice pythonic style interface....

**Comment by agramfort** [comment]
@papadop I find the constructors for Sensors class quiet confusing now. I am plead guilty to some extend. Basically we support labels or not, weights or not etc.

**Comment by larsoner** [comment]
On Windows it seems like when doing `om.Geometry(geom_file, cond_file)`, the two files cannot be deleted afterward:

https://dev.azure.com/mne-tools/mne-python/_build/results?buildId=21617&view=logs&j=305851a9-a7bb-55db-0042-7e2b6f48aa1c&t=4d37777d-f36a-53aa-9217-6386d15dddcd&l=3479

```
E   PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\VSSADM~1\\AppData\\Local\\Temp\\openmeeg-io-t2wktag7\\tmp.geom'
```

These should be read immediately on `Geometry` instantiation then the file pointers closed, right? It seems like this is not the case for Windows.

**Comment by larsoner** [comment]
In an effort to expose `om.Integrator` in Python, I tried adding this to `openmeeg.i`:
```
%include <integrator.h>
```
but SWIG is not happy about it:
```
/Users/larsoner/python/openmeeg/OpenMEEG/include/integrator.h:45: Error: Syntax error in input(3).
```
which points to this line

https://github.com/openmeeg/openmeeg/blob/b00b2dc295a7f8923600f2f7adb06554ba83e26d/OpenMEEG/include/integrator.h#L45

I assume this is the `decltype(auto)` stuff -- @papadop can this be avoided? It looks like it was added in the last month in https://github.com/openmeeg/openmeeg/pull/503 (the un-revert). Maybe it can be reworked somehow so that SWIG can handle it...

If we can get this to work, this would fix one of the `XXX` in tests, and allow use to remove the `HeadMat(&geo, const bool verbose)` wrapper introduced in https://github.com/openmeeg/openmeeg/pull/589 in favor of the `HeadMat(&geo, &Integrator, const bool verbose)` wrapper (which we can't use in Python at the moment because we can't instatiate `om.Integrator()` in Python.

**Comment by larsoner** [comment]
Okay I found a workaround for this SWIG problem in https://github.com/openmeeg/openmeeg/pull/589 by protecting the header def with a `#ifndef SWIGPYTHON`. I *think* the only side effect is that we cannot call `integrator.integrate(...)` from Python, but I don't think we ever want to do that anyway! It would be nice not to have this conditional, though, if there is an easy way around it, but I'll mark it as done above.

**Comment by papadop** [comment]
Just a naive question: Is there a specific reason you want integrators exposed. I know they are now part of the interface, but I thought that python code could rely only on the default value of the integrators...

**Comment by larsoner** [comment]
There is already a `XXX` in the tests where @agramfort wanted to change/test them. One reason I would like them exposed is to try to speed up the tests in MNE-Python if we can live with slightly less good integration quality
